# Stage 1 : build
FROM node:20-alpine AS build
WORKDIR /app

ARG REACT_APP_BACK_BASEURL
ENV REACT_APP_BACK_BASEURL=${REACT_APP_BACK_BASEURL}

COPY package*.json ./
RUN npm install --force
COPY . .
RUN npm run build  
# Stage 2 : production NGINX
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html  
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]